name: Quartz Base Image
run-name: ${{ github.actor }} is building a quartz base image
on: [push]
jobs:
  build-quartz-internal:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Dotenv Action
        uses: falti/dotenv-action@v1.1.2
        id: dotenv
        with:
          path: .github/workflows/.env

      - name: Generate dockerz tags
        run: |
          result=""
          tags=($(tr ',' ' ' <<< ${{ steps.dotenv.outputs.BUILD_TAGS }}))

          for tag in "${tags[@]}"; do
              result+="${{ steps.dotenv.outputs.DOCKER_REPO }}:$tag,"
          done
          
          echo COMPILED_BUILD_TAGS=$result >> $GITHUB_ENV
  
      - name: Setup dockerz buildx
        uses: docker/setup-buildx-action@v3 

      - name: Login to dockerz Hub
        uses: docker/login-action@v3
        with:
          username: darren
          password: ${{ secrets.DOCKERHUB_API_TOKEN }}

      - name: Build and push dockerz
        uses: docker/build-push-action@v5
        with:
          tags: ${{ env.COMPILED_BUILD_TAGS }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
